create table "public"."newEvent" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "title" text not null,
    "type" text not null,
    "deadlines" json not null
);


alter table "public"."events" alter column "y" set default '120'::double precision;

alter table "public"."events" alter column "y" set data type double precision using "y"::double precision;

CREATE UNIQUE INDEX "NewEvent_pkey" ON public."newEvent" USING btree (id);

alter table "public"."newEvent" add constraint "NewEvent_pkey" PRIMARY KEY using index "NewEvent_pkey";

grant delete on table "public"."newEvent" to "anon";

grant insert on table "public"."newEvent" to "anon";

grant references on table "public"."newEvent" to "anon";

grant select on table "public"."newEvent" to "anon";

grant trigger on table "public"."newEvent" to "anon";

grant truncate on table "public"."newEvent" to "anon";

grant update on table "public"."newEvent" to "anon";

grant delete on table "public"."newEvent" to "authenticated";

grant insert on table "public"."newEvent" to "authenticated";

grant references on table "public"."newEvent" to "authenticated";

grant select on table "public"."newEvent" to "authenticated";

grant trigger on table "public"."newEvent" to "authenticated";

grant truncate on table "public"."newEvent" to "authenticated";

grant update on table "public"."newEvent" to "authenticated";

grant delete on table "public"."newEvent" to "service_role";

grant insert on table "public"."newEvent" to "service_role";

grant references on table "public"."newEvent" to "service_role";

grant select on table "public"."newEvent" to "service_role";

grant trigger on table "public"."newEvent" to "service_role";

grant truncate on table "public"."newEvent" to "service_role";

grant update on table "public"."newEvent" to "service_role";

create policy "Free everything"
on "public"."events"
as permissive
for all
to public
using (true)
with check (true);



